name: Build and Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.17.0]

    steps:
      - name: Checkout ğŸ›ï¸ Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v2

      - name: Install and Test ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run lint
          npm run test

      - name: Upload node_modules for test
        uses: actions/upload-artifact@v1
        with:
          name: deps
          path: node_modules

  deploy:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [10.17.0]

    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout ğŸ›ï¸ Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Download deps for test
        uses: actions/download-artifact@v1
        with:
          name: deps
      - shell : bash
        run: |
          cp -aR deps/node_modules .

      - name: Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm run build

      - name: Install SSH Client ğŸ”‘
        uses: webfactory/ssh-agent@v0.2.0 # This step installs the ssh client into the workflow run. There's many options available for this on the action marketplace.
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3-test
        with:
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
          SSH: true # SSH must be set to true so the deploy action knows which protocol to deploy with.

      - name : Make build in github-actions-test
        run : |
          mkdir github-actions-test
          mv ./build/* ./github-actions-test/
          mv ./github-actions-test ./build/
          mv ./build/github-actions-test/index.html ./build/
      
      - name: Deploy to docker
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: dhruvingbc/github-actions-test
          tag: node-0.0.${GITHUB_RUN_NUMBER}
          registry: docker.io
          dockerfile: "./Docker/Dockerfile"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}